PPAP_Proiect/Pages/User/Edit.cshtml.cs
using System.Linq.Expressions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Data.SqlClient;
using Org.BouncyCastle.Security;
using PPAP_Proiect.Data;
using PPAP_Proiect.Models;

namespace PPAP_Proiect.Pages.User
{
    public class EditModel : PageModel
    {
        private readonly DBConectare _db;
        private readonly FunctiiUtilizator _fu;
        public EditModel (DBConectare db, FunctiiUtilizator fu)
        {
            _db = db;
			_fu = fu;
        }

        [BindProperty]
        public Utilizator userEdit { get; set; }
        [BindProperty]
        public string parolaConfirmare { get; set;  }
        public IActionResult OnGet()
        {
            int? userId = HttpContext.Session.GetInt32("userId");

            if(userId == null)
            {
                return RedirectToPage("/Index");
            }

			userEdit = _fu.GetUtilizatorSession((int)userId);
            return Page();
        }

        public IActionResult OnPost()
        {

			int? userId = HttpContext.Session.GetInt32("userId");
			if (userId == null) return RedirectToPage("/Index");

			int prenumeValid = FunctiiUtilizator.IsValidNume(userEdit.Prenume);
            int numeValid = FunctiiUtilizator.IsValidNume(userEdit.Nume);
            int cnpValid = FunctiiUtilizator.IsValidCnp(userEdit.Cnp);
            int emailValid = FunctiiUtilizator.IsValidEmail(userEdit.Email);

			if (prenumeValid == 0)
				ModelState.AddModelError("eroarePrenume", "Prenumele trebuie sa contina doar litere!");


			if (numeValid == 0)
				ModelState.AddModelError("eroareNume", "Numele trebuie sa contina doar litere!");


			switch (cnpValid)
			{
				case -2:
					ModelState.AddModelError("eroareCNP", "CNP-ul nu trebuie sa contina litere!");
					break;
				case 0:
					ModelState.AddModelError("eroareCNP", "CNP-ul trebuie sa aiba lungimea 13!");
					break;
				default:
					break;
			}

			switch (emailValid)
			{
				case 0:
					ModelState.AddModelError("eroareEmail", "Email-ul trebuie sa fie sub forma de 'xxxx@xxxx.xxx' !");
					break;

			}

			if (!string.IsNullOrEmpty(userEdit.Parola))
			{
				int parolaValida = FunctiiUtilizator.IsValidPassword(userEdit.Parola);
				int parolaConfirmata = FunctiiUtilizator.PasswordEqual(parolaConfirmare, userEdit.Parola);

				switch (parolaValida)
				{
					case -2:
						ModelState.AddModelError("eroareParola", "Parola trebuie sa aiba o lungime de cel putin 8 caractere!");
						break;
					case 0:
						ModelState.AddModelError("eroareParola", "Parola trebuie sa aiba un caracter de tip A-Z, unul de tip a-z si unul special (ex. @!#$%....)!");
						break;
				}

				if (parolaConfirmata == 0 && parolaValida == 1)
					ModelState.AddModelError("eroareParolaConfirmare", "Cele doua parole puse de tine nu sunt egale!");
			}
			else
			{
				ModelState.Remove("userEdit.Parola");
				ModelState.Remove("parolaConfirmare");
			}

			if (!ModelState.IsValid)
				return Page();


			string parolaHash;

			if (string.IsNullOrEmpty(userEdit.Parola))
			{
				parolaHash = _fu.GetUtilizatorSession((int)userId).Parola;
			}
			else
			{
				parolaHash = FunctiiUtilizator.HashParola(userEdit.Parola);
			}

			using (SqlConnection conn = _db.GetConnection())
			{
				if (conn.State == System.Data.ConnectionState.Closed)
					conn.Open();

				using (SqlCommand cmd = new SqlCommand("sp_Utilizator_Edit", conn))
				{
					cmd.CommandType = System.Data.CommandType.StoredProcedure;
					cmd.Parameters.AddWithValue("@email", userEdit.Email);
					cmd.Parameters.AddWithValue("@nume", userEdit.Nume);
					cmd.Parameters.AddWithValue("@prenume", userEdit.Prenume);
					cmd.Parameters.AddWithValue("@cnp", userEdit.Cnp);
					cmd.Parameters.AddWithValue("@parola", parolaHash);
					cmd.Parameters.AddWithValue("@userId", userId);

					try { 
					cmd.ExecuteNonQuery();
					}
					catch(Exception e)
					{
						ModelState.AddModelError("eroareBazaDeDate", "Eroare: " + e.Message);
						return Page();
					}
				}
			}

			return RedirectToPage("/Index" , new { status = "succes_edit"});
		}
    }
}

PPAP_Proiect/Pages/User/EmailConfirmare.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Data.SqlClient;
using PPAP_Proiect.Data;
using PPAP_Proiect.Models;
using PPAP_Proiect.Services;

namespace PPAP_Proiect.Pages.User
{
    public class EmailConfirmareModel : PageModel
    {
        private readonly IConfiguration _config;
        private readonly DBConectare _db;
        private readonly FunctiiUtilizator _fu;
        private readonly UserEmailService _ues;

        public string tokenConfirmare; 
        public EmailConfirmareModel(IConfiguration config, DBConectare db, FunctiiUtilizator fu, UserEmailService ues)
        {
            _config = config;
            _db = db;
            _fu = fu;
            _ues = ues;
        }

        public Utilizator userCurent;
        public IActionResult OnGet()
        {
            int? userId = HttpContext.Session.GetInt32("userId");

            if(userId == null)
            {
                return RedirectToPage("/Index");
            }


            userCurent = _fu.GetUtilizatorSession((int)userId);

            if(userCurent.ContVerificat == true)
            {
				HttpContext.Session.SetString("mesajSucces", "Cont deja verificat!");
				return RedirectToPage("/Index");
            }

            string configVerificare = _config["SecretKeys:confirmareCont"];
		    tokenConfirmare = FunctiiUtilizator.HashToken(userCurent.Nume, userCurent.Cnp, configVerificare);

			string linkConfirmare = Url.Page(
	        "/User/EmailConfirmare",
	        pageHandler: "Confirm",
	        values: new { token = tokenConfirmare },
	        protocol: Request.Scheme
            );


			string numeUser = $"{userCurent.Nume} {userCurent.Prenume}";
            _ues.TrimitereConfirmareCont(numeUser, userCurent.Email, linkConfirmare);

			HttpContext.Session.SetString("mesajSucces", "Email de confirmare trimis pe mailul " + userCurent.Email + "!");
			return RedirectToPage("/Index");
		}

        public IActionResult OnGetConfirm(string token)
        {
			int? userId = HttpContext.Session.GetInt32("userId");

			if (userId == null)
				return RedirectToPage("/Index");

            var user = _fu.GetUtilizatorSession((int)userId);

            if(user.ContVerificat == true)
            {
                HttpContext.Session.SetString("mesajSucces", "Cont deja verificat!");
                return RedirectToPage("/Index");
            }

            string configVerificare = _config["SecretKeys:confirmareCont"];
            string tokenFormat = FunctiiUtilizator.HashToken(user.Nume, user.Cnp, configVerificare);

            if(token != tokenFormat)
            {
				HttpContext.Session.SetString("mesajEroare", "Tokenul dat de tine nu este bun! Incearca din nou pe noul mail trimis!");
                Console.WriteLine(HttpContext.Session.GetString("mesajEroare"));
				return RedirectToPage("/Index");
            }
            else {
                using (SqlConnection conn = _db.GetConnection())
                {
                    if (conn.State == System.Data.ConnectionState.Closed)
                        conn.Open();

                    using (SqlCommand cmd = new SqlCommand("sp_Utilizator_Confirm", conn))
                    {
                        cmd.CommandType = System.Data.CommandType.StoredProcedure;
                        cmd.Parameters.AddWithValue("@id", user.Id);
                        try
                        {
                            cmd.ExecuteNonQuery();
                        }
                        catch(Exception e)
                        {
							HttpContext.Session.SetString("mesajEroare", "Eroare : " + e.Message);
                            Console.WriteLine(e.Message);
							return RedirectToPage("/Index");
                        }
                    }
                }
            }

			HttpContext.Session.SetString("mesajSucces", "Cont confirmat cu succes!");
            Console.WriteLine("Ura");
            return RedirectToPage("/Index");
		}
    }
}

PPAP_Proiect/Pages/User/Logout.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace PPAP_Proiect.Pages.User
{
    public class LogoutModel : PageModel
    {
        public IActionResult OnGet()
        {
            HttpContext.Session.Clear();
            return RedirectToPage("/Index");
        }
    }
}

PPAP_Proiect/Pages/User/ResetParola.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Data.SqlClient;
using Microsoft.IdentityModel.Tokens;
using PPAP_Proiect.Data;
using PPAP_Proiect.Models;
using PPAP_Proiect.Services;

namespace PPAP_Proiect.Pages.User
{
    public class ResetParolaModel : PageModel
    {
        private readonly IConfiguration _config;
        private readonly DBConectare _db;
        private readonly FunctiiUtilizator _fu;
        private readonly UserEmailService _ues;

        [BindProperty]
        public string tokenResetare { get; set; }
        [BindProperty]
        public int UserId { get; set; }

        [BindProperty]
        public string parolaSchimbare { get; set; }
        [BindProperty]
        public string parolaSchimbareConfirmare { get; set; }

        public ResetParolaModel(IConfiguration config, DBConectare db, FunctiiUtilizator functiiUtilizator, UserEmailService ues)
        {
            _config = config;
            _db = db;
            _fu = functiiUtilizator;
            _ues = ues;
        }


        public string getConfigReset()
        {
            return _config["SecretKeys:resetareparolaCont"];
        }

        public IActionResult OnGet()
        {
            int? userId = HttpContext.Session.GetInt32("userId");

            if (userId != null)
            {
                HttpContext.Session.SetString("mesajEroare", "Nu ai acces, modifica parola din panoul de edit!");
                return RedirectToPage("/Index");
            }

            return Page();
        }

        public IActionResult OnPost(string emailsaucnp)
        {
            Utilizator user = null;

            if (string.IsNullOrEmpty(emailsaucnp))
            {
                ModelState.AddModelError("mesajEroare", "Camp gol!");
            }

            int emailValid = FunctiiUtilizator.IsValidEmail(emailsaucnp);
            int cnpValid = FunctiiUtilizator.IsValidCnp(emailsaucnp);

            if(emailValid != 1 && cnpValid != 1)
            {
                ModelState.AddModelError("mesajEroareCNPsauEmail", "Input invalid!");
            }

            try
            {
               user = _fu.GetUserByEmailsauCNP(emailsaucnp);
            }
            catch (Exception e)
            {
                ModelState.AddModelError("mesajEroare", "Eroare : " + e.Message);
            }

            if (user == null)
            {
                ModelState.AddModelError("mesajEroare", "Utilizator inexistent in baza noastra de date");
                return Page();
            }

            string configReset = getConfigReset();

            tokenResetare = FunctiiUtilizator.HashToken(user.Nume, user.Cnp, configReset);
            UserId = user.Id;
            string linkConfirmare = Url.Page(
                "/User/ResetParola",
                pageHandler: "Resetare",
                values: new { token = tokenResetare, userId = user.Id },
                protocol: Request.Scheme
                );

            string numeUser = $"{user.Nume} {user.Prenume}";
            _ues.TrimiteResetaerParola(numeUser, user.Email, linkConfirmare);

            HttpContext.Session.SetString("mesajSucces", "Email de resetare trimis pe mailul " + user.Email);
            return RedirectToPage("/User/Login");
        }

        public IActionResult OnGetResetare(string token, int? userId)
        {

            
            if (userId == null)
            {
                return RedirectToPage("/User/Login");
            }

            Utilizator user = _fu.GetUtilizatorSession((int)userId);


            if (user == null)
            {
                HttpContext.Session.SetString("eroareLogin", "Ceva nu a mers bine!");
                return RedirectToPage("/User/Login");
            }

            UserId = (int)userId;

            tokenResetare = FunctiiUtilizator.HashToken(user.Nume, user.Cnp, this.getConfigReset());

            if (!string.Equals(token, tokenResetare))
            {
                ModelState.AddModelError("mesajEroare", "Token-urile nu sunt egale!");
                return Page();

            }

            return Page();

        }

        public IActionResult OnPostResetare()
        {
            int userId = UserId;
            string token;

            Utilizator user = _fu.GetUtilizatorSession((int)userId);


            if (user == null)
            {
                HttpContext.Session.SetString("eroareLogin", "Ceva nu a mers bine!");
                return RedirectToPage("/User/Login");
            }

            token = FunctiiUtilizator.HashToken(user.Nume, user.Cnp, this.getConfigReset());

            if (!string.Equals(token, tokenResetare))
            {
                HttpContext.Session.SetString("eroareLogin", "Token-urile nu sunt egale, mai incearca odata!");
                Console.WriteLine("tokenul din clasa este egal cu " + tokenResetare + " si tokenul format este egal cu " + token);
                return RedirectToPage("/User/Login");

            }
            int parolaValida = FunctiiUtilizator.IsValidPassword(parolaSchimbare);
            int parolaEgala = FunctiiUtilizator.PasswordEqual(parolaSchimbare, parolaSchimbareConfirmare);

            switch (parolaValida)
            {
                case -1:
                    ModelState.AddModelError("eroareParola", "Camp parola este gol!");
                    break;
                case -2:
                    ModelState.AddModelError("eroareParola", "Parola trebuie sa aiba o lungime de cel putin 8 caractere!");
                    break;
                case 0:
                    ModelState.AddModelError("eroareParola", "Parola trebuie sa aiba un caracter de tip A-Z, unul de tip a-z si unul special (ex. @!#$%....)!");
                    break;
            }

            if (parolaEgala == 0 && parolaValida == 1)
                ModelState.AddModelError("eroareParolaConfirmare", "Cele doua parole puse de tine nu sunt egale!");

            if (!ModelState.IsValid)
                return Page();

            string parolaHash = FunctiiUtilizator.HashParola(parolaSchimbare);

            using (SqlConnection conn = _db.GetConnection())
            {
                if (conn.State == System.Data.ConnectionState.Closed)
                    conn.Open();

                using (SqlCommand cmd = new SqlCommand("sp_Utilizator_ResetParola", conn))
                {
                    cmd.CommandType = System.Data.CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@parola", parolaHash);
                    cmd.Parameters.AddWithValue("@userId", userId); //care nu exista, uof
                    var returnParam = new SqlParameter();
                    returnParam.Direction = System.Data.ParameterDirection.ReturnValue;
                    cmd.Parameters.Add(returnParam);

                    try
                    {
                        cmd.ExecuteNonQuery();
                        int result = (int)returnParam.Value;

                        switch (result)
                        {
                            case 0:
                                ModelState.AddModelError("mesajEroare", "Ceva nu a mers bine!");
                                Console.WriteLine("Ceva nu a mers bine la prola bagmias pula in ea de parola dracu!");
                                return Page();
                        }
                    }
                    catch (Exception e)
                    {
                        ModelState.AddModelError("mesajEroare", "Eroare: " + e.Message);
                        Console.WriteLine(e.Message);
                        return Page();
                    }
                }
            }
            HttpContext.Session.SetString("mesajSucces", "Parola resetata cu succes!");
            return RedirectToPage("/User/Login");
        }
    }
}

PPAP_Proiect/Pages/User/Edit.cshtml
@page
@model PPAP_Proiect.Pages.User.EditModel
@{
    ViewData["Title"] = "Editare Profil";
}

<style>

    .form-row {
        display: flex;
        flex-wrap: wrap;
        justify-content: space-between; 
    }

    .form-col {
        width: 48%; 
        margin-bottom: 15px;
    }

    }
</style>

<div class="auth-wrapper">
    <div class="auth-card">
        <h2>Editare profil utilizator</h2>

        <form method="post">

            <div class="form-row">

                <div class="form-group form-col">
                    <label>Nume:</label>
                    <input asp-for="userEdit.Nume" placeholder="Introdu numele" />
                    <span class="text-danger">@Model.ModelState["eroareNume"]?.Errors.FirstOrDefault()?.ErrorMessage</span>
                </div>

                <div class="form-group form-col">
                    <label>Prenume:</label>
                    <input asp-for="userEdit.Prenume" placeholder="Introdu prenumele" />
                    <span class="text-danger">@Model.ModelState["eroarePrenume"]?.Errors.FirstOrDefault()?.ErrorMessage</span>
                </div>

                <div class="form-group form-col">
                    <label>Email:</label>
                    <input asp-for="userEdit.Email" type="email" placeholder="email@exemplu.ro" />
                    <span class="text-danger">@Model.ModelState["eroareEmail"]?.Errors.FirstOrDefault()?.ErrorMessage</span>
                </div>

                <div class="form-group form-col">
                    <label>CNP:</label>
                    <input asp-for="userEdit.Cnp" placeholder="Cod Numeric Personal" />
                    <span class="text-danger">@Model.ModelState["eroareCNP"]?.Errors.FirstOrDefault()?.ErrorMessage</span>
                </div>

                <div class="form-group form-col">
                    <label>Parolă:</label>
                    <input asp-for="userEdit.Parola" type="password" placeholder="••••••••" />
                    <span class="text-danger">@Model.ModelState["eroareParola"]?.Errors.FirstOrDefault()?.ErrorMessage</span>
                </div>

                <div class="form-group form-col">
                    <label>Confirmare parolă:</label>
                    <input asp-for="parolaConfirmare" type="password" placeholder="••••••••" />
                    <span class="text-danger">@Model.ModelState["eroareParolaConfirmare"]?.Errors.FirstOrDefault()?.ErrorMessage</span>
                </div>

            </div> <button type="submit" class="btn-primary" style="margin-top: 10px;">Salvează modificările</button>

            <div class="auth-footer">
                <a asp-page="/User/Index" class="auth-link">Înapoi la profil</a>
            </div>

        </form>
    </div>
</div>

PPAP_Proiect/Pages/User/EmailConfirmare.cshtml
@page
@model PPAP_Proiect.Pages.User.EmailConfirmareModel
@{
}

PPAP_Proiect/Pages/User/Login.cshtml
@page
@model PPAP_Proiect.Pages.User.LoginModel
@{
    ViewData["Title"] = "Login";
    string mesajSucces = HttpContext.Session.GetString("mesajSucces");
    string eroareLogin = HttpContext.Session.GetString("eroareLogin");

    if(mesajSucces != null)
        HttpContext.Session.Remove("mesajSucces");

    if (eroareLogin != null)
        HttpContext.Session.Remove("eroareLogin");
}

<div class="auth-wrapper">
    <div class="auth-card">
        <h2>Autentificare</h2>

        <form method="post">
            @if (Model.ModelState["eroareLogin"]?.Errors.Count > 0 || eroareLogin != null)
            {
                <div class="form-group">
                    <span class="text-danger">@(Model.ModelState["eroareLogin"]?.Errors.FirstOrDefault()?.ErrorMessage ?? eroareLogin)</span>
                </div>
            }

            @if (Model.ModelState["mesajSucces"] != null || mesajSucces != null)
            {
                <div class="form-group">
                    <span class="text-success" style="color: green; font-weight: bold;">
                        @(Model.ModelState["mesajSucces"]?.Errors.FirstOrDefault()?.ErrorMessage ?? mesajSucces)
                    </span>
                </div>
            }
            <div class="form-group">
                <label>Email sau CNP:</label>
                <input asp-for="EmailsauCNP" type="text" placeholder="nume@exemplu.ro / 1231231231231" />
                <span class="text-danger">@Model.ModelState["eroareEmailCNP"]?.Errors.FirstOrDefault()?.ErrorMessage</span>
            </div>

            <div class="form-group">
                <label>Parolă:</label>
                <input asp-for="parola" type="password" placeholder="••••••••" />
                <span class="text-danger">@Model.ModelState["eroareParola"]?.Errors.FirstOrDefault()?.ErrorMessage</span>
            </div>

            <button type="submit" class="btn-primary">Intră în cont</button>


            <div class="auth-footer">
                <span>Nu ai cont?</span>
                <a asp-page="/User/Register" class="auth-link">Înregistrează-te</a>
            </div>

            <div class="auth-footer" style="margin-top: 0.5rem;">
                <span>Ai uitat parola?</span>
                <a asp-page="/User/ResetParola" class="auth-link">Resetează aici</a>
            </div>
        </form>
    </div>
</div>

PPAP_Proiect/Pages/User/Logout.cshtml
@page
@model PPAP_Proiect.Pages.User.LogoutModel
@{
}

PPAP_Proiect/Pages/User/Register.cshtml
@page
@model PPAP_Proiect.Pages.User.RegisterModel
@{
    ViewData["Title"] = "Register";
}

<div class="auth-wrapper">
    <div class="auth-card">
        <h2>Creare cont utilizator</h2>

        <form method="post">
            @if (Model.ModelState["eroareBazaDeDate"]?.Errors.Count > 0)
            {
                <div class="form-group">
                    <span class="text-danger">@Model.ModelState["eroareBazaDeDate"]?.Errors.FirstOrDefault()?.ErrorMessage</span>
                </div>
            }

            <div class="form-group">
                <label>Nume:</label>
                <input asp-for="userNou.Nume" placeholder="Introdu numele" />
                <span class="text-danger">@Model.ModelState["eroareNume"]?.Errors.FirstOrDefault()?.ErrorMessage</span>
            </div>

            <div class="form-group">
                <label>Prenume:</label>
                <input asp-for="userNou.Prenume" placeholder="Introdu prenumele" />
                <span class="text-danger">@Model.ModelState["eroarePrenume"]?.Errors.FirstOrDefault()?.ErrorMessage</span>
            </div>

            <div class="form-group">
                <label>Email:</label>
                <input asp-for="userNou.Email" type="email" placeholder="email@exemplu.ro" />
                <span class="text-danger">@Model.ModelState["eroareEmail"]?.Errors.FirstOrDefault()?.ErrorMessage</span>
            </div>

            <div class="form-group">
                <label>CNP:</label>
                <input asp-for="userNou.Cnp" placeholder="Cod Numeric Personal" />
                <span class="text-danger">@Model.ModelState["eroareCNP"]?.Errors.FirstOrDefault()?.ErrorMessage</span>
            </div>

            <div class="form-group">
                <label>Parolă:</label>
                <input asp-for="userNou.Parola" type="password" placeholder="••••••••" />
                <span class="text-danger">@Model.ModelState["eroareParola"]?.Errors.FirstOrDefault()?.ErrorMessage</span>
            </div>

            <div class="form-group">
                <label>Confirmare parolă:</label>
                <input asp-for="parolaConfirmare" type="password" placeholder="••••••••" />
                <span class="text-danger">@Model.ModelState["eroareParolaConfirmare"]?.Errors.FirstOrDefault()?.ErrorMessage</span>
            </div>

            <button type="submit" class="btn-primary">Creează cont</button>

            <div class="auth-footer">
                <span>Ai deja un cont?</span>
                <a asp-page="/User/Login" class="auth-link">Autentifică-te</a>
            </div>
        </form>
    </div>
</div>

PPAP_Proiect/Pages/User/ResetParola.cshtml
@page
@model PPAP_Proiect.Pages.User.ResetParolaModel
@{
    ViewData["Title"] = "Resetare Parolă";
}


<div class="auth-wrapper">
    <div class="auth-card">
        <h2>@ViewData["Title"]</h2>

        @if (!ModelState.IsValid)
        {
            <div class="text-danger" style="text-align: center; margin-bottom: 1rem; font-size: 0.9rem;">
                <div asp-validation-summary="ModelOnly"></div>
                <span>@Html.ValidationMessage("mesajEroare")</span>
            </div>
        }

        @if (string.IsNullOrEmpty(Model.tokenResetare))
        {
            <form method="post">
                <div class="form-group">
                    <label for="emailsaucnp">Email sau CNP</label>
                    <input type="text" id="emailsaucnp" name="emailsaucnp" placeholder="Introdu adresa de email sau CNP-ul" />
                    <span class="text-danger">@Html.ValidationMessage("mesajEroareCNPsauEmail")</span>
                </div>

                <button type="submit" class="btn-primary">Trimite Link Resetare</button>
            </form>
        }
        else
        {
            <form method="post" asp-page-handler="Resetare">
                <input type="hidden" asp-for="UserId" />
                <input type="hidden" asp-for="tokenResetare" />

                <div class="form-group">
                    <label asp-for="parolaSchimbare">Parola Nouă</label>
                    <input asp-for="parolaSchimbare" type="password" placeholder="Introdu parola nouă" required />
                    <span class="text-danger">@Html.ValidationMessage("eroareParola")</span>
                </div>

                <div class="form-group">
                    <label asp-for="parolaSchimbareConfirmare">Confirmă Parola Nouă</label>
                    <input asp-for="parolaSchimbareConfirmare" type="password" placeholder="Confirmă parola" required />
                    <span class="text-danger">@Html.ValidationMessage("eroareParolaConfirmare")</span>
                </div>

                <button type="submit" class="btn-primary">Salvează Noua Parolă</button>
            </form>
        }

        <div class="auth-footer">
            <a href="/User/Login" class="auth-link">Înapoi la Autentificare</a>
        </div>
    </div>
</div>